# Generated by Django 3.1.4 on 2020-12-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201223_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type_of_blog', models.CharField(choices=[('TECh', 'Technology'), ('FINANCE', 'Financial'), ('CONS', 'Consumer')], max_length=20)),
            ],
        ),
    ]
