# Generated by Django 3.1.4 on 2020-12-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='type_of_blog',
        ),
        migrations.AddField(
            model_name='subject',
            name='title',
            field=models.CharField(choices=[('tech', 'Technology'), ('finance', 'Financial'), ('cons', 'Consumer'), ('cyber', 'Cybersecurity')], default='DEFAULT VALUE', max_length=25),
        ),
    ]
