# Generated by Django 3.1.4 on 2020-12-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201224_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
