# Generated by Django 3.1.4 on 2020-12-24 16:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('tech', 'Technology'), ('finance', 'Financial'), ('cons', 'Consumer'), ('cyber', 'Cybersecurity')], default='DEFAULT VALUE', max_length=23),
        ),
    ]
