# Generated by Django 3.1.4 on 2021-02-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
